sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

cache:
  - ccache
  - directories:
      - $HOME/.ccache

# command to install dependencies
install:
  - unset CCACHE_DISABLE
  - export CCACHE_DIR=$HOME/.ccache
  - export CC="ccache gcc-4.8"
  - export CXX="ccache g++-4.8"
  - ccache --show-stats
  - travis_retry pip install -r requirements.txt
  - python setup.py install
  # - pip install -r requirements.txt
  - pip install tox-travis
# command to run tests
script: tox
# Configure email notifications
notifications:
  email: false
