sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.8.post1-cp27-none-linux_x86_64.whl
  - pip install https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.8.post1-cp35-cp35m-linux_x86_64.whl
  - pip install https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.8.post1-cp36-cp36m-linux_x86_64.whl
  - pip install tox-travis
# command to run tests
script: tox
# Configure email notifications
notifications:
  email: false
